version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "@angular/*"
      versions: ["17.x"]
    - dependency-name: "@angular-devkit/build-angular"
      versions: ["17.x"]
    - dependency-name: "@angular-eslint/*"
      versions: ["17.x"]
    - dependency-name: "ng-packagr"
      versions: ["17.x"]
    - dependency-name: "zone"
      versions: ["0.14.0", "0.14.1", "0.14.2"]
    - dependency-name: "typescript"
      versions: ["5.2.x", "5.3.x"]
